export * from './movies/movies.component'
export * from './header/header.component'
export * from './auth/login/auth-login.component';
export * from './auth/register/auth-register.component';
export * from './auth/layout.component';
export * from './home/home.component';
export * from './cinema/cinema-movies.component';
export * from './cinema/movie-info/movie-card.component';
export * from './cinema/hall/hall.component';
