/**
 * cinema-rest-v1
 * Api and Models
 *
 * OpenAPI spec version: 1.19.0-rc (787f8c4051c7ac9bfaf2ff9a03df6ffcb85234ff)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Role } from './role';


export interface RegisterRequest { 
    firstname?: string;
    lastname?: string;
    email?: string;
    password?: string;
    role?: Role;
}
